### ISSUE TITLE
after update to 2.91.3 UX flow changed and various bugs

### ISSUE THREAD

**Issue by uvwild** [projecthamster/xfce4-hamster-plugin#45]
1. the  timer is not  updated anymore as before

2. when editing an entry suddenly multiple parts showed up split by tags?!?

i have the impression there is something not working right. 
maybe the tag handling?
i dont have the time to dig deep, but the last update was clearly a step back in usabilty

**Comment by GeraldJansen** [comment]
Just out of curiosity, are you talking about hamster-applet 2.91.3 from November, 2010? I suspect recent versions of the xfce4 plugin have have only been tested with a more recent Hamster version.

**Comment by aquaherd** [comment]
Indeed the latest version targeting hamster-applet was v1.7 from 2014. 
Development stalled for some time afterwards.

Around mid 2020 xfce4 dropped gtk2 and hamster 3.0 with gtk3 and python3 appeared in debian buster-backports unseating hamster-applet for me so I started porting it to the new situation with v1.8 onwards. 

April 2021 I merged in-place edits with v1.14 since I was using it in WSL1 and the gtk3-hamster was too slow.

End of 2021 I only modernized the build and took 3 releases to get it right.

So I would really like to know which version worked for you and which did not. If you can't dig deeper I can't help you.
